apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: arcadia-fastapi
  labels:
    app: arcadia-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arcadia-api
  template:
    metadata:
      labels:
        app: arcadia-api
    spec:
      containers:
        - image: gcu-profit-dev.kr-central-2.kcr.dev/arcadia-nextjs/fastapi:31
          name: fastapi
          ports:
            - containerPort: 8000
              name: http
      imagePullSecrets:
        - name: kic-registry
  strategy:
    blueGreen:
      activeService: arcadia-fastapi-active
      previewService: arcadia-fastapi-preview
      autoPromotionEnabled: true