# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: arcadia-fastapi-hpa
#   labels:
#     app: arcadia-api
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: arcadia-fastapi
#   minReplicas: 3  # 최소 Replica 수
#   maxReplicas: 5  # 최대 Replica 수
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 70  # 평균 CPU 사용률이 50%가 되도록 조정
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: arcadia-springboot-login-hpa
#   labels:
#     app: arcadia-api
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: arcadia-springboot-login
#   minReplicas: 3  # 최소 Replica 수
#   maxReplicas: 5  # 최대 Replica 수
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 70  # 평균 CPU 사용률이 50%가 되도록 조정
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: arcadia-springboot-board-hpa
#   labels:
#     app: arcadia-api
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: arcadia-springboot-board
#   minReplicas: 3  # 최소 Replica 수
#   maxReplicas: 5  # 최대 Replica 수
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 50  # 평균 CPU 사용률이 50%가 되도록 조정

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: arcadia-fastapi-hpa
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: arcadia-fastapi
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: arcadia-springboot-login-hpa
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: arcadia-springboot-login
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: arcadia-springboot-board-hpa
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: arcadia-springboot-board
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80