apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arcadia-ingress
  labels:
    app: arcadia-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  selector:
    matchLabels:
      app: arcadia-api
  rules:
  - host: arcadia-api.p-e.kr
    http:
      paths:
      - path: /fastapi
        pathType: Prefix
        backend:
          service:
            name: arcadia-fastapi-service
            port:
              number: 80
      - path: /login
        pathType: Prefix
        backend:
          service:
            name: arcadia-springboot-login-service
            port:
              number: 80
      - path: /board
        pathType: Prefix
        backend:
          service:
            name: arcadia-springboot-board-service
            port:
              number: 80
  tls:
    - hosts:
      - arcadia-api.p-e.kr
      secretName: arcadia-api-tls
status:
  loadBalancer:
    ingress:
      - {}