apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: arcadia-springboot-login
  labels:
    app: arcadia-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arcadia-api
  template:
    metadata:
      labels:
        app: arcadia-api
    spec:
      containers:
        - image: gcu-profit-dev.kr-central-2.kcr.dev/arcadia-nextjs/springboot-login:27
          name: springboot-login
          ports:
            - containerPort: 8080
              name: http
          env:
          - name: SPRING_REDIS_HOST
            value: redis-master
          - name: SPRING_REDIS_PORT
            value: "6379"
      imagePullSecrets:
        - name: kic-registry
  strategy:
    blueGreen:
      activeService: arcadia-springboot-login-active
      previewService: arcadia-springboot-login-preview
      autoPromotionEnabled: true