apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sunoapi-pvc
  labels:
    app: arcadia-api
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi