apiVersion: v1
kind: Service
metadata:
  name: sunoapi-service-active
  labels:
    app: arcadia-api
spec:
  selector:
    app: arcadia-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 5601
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: sunoapi-service-preview
  labels:
    app: arcadia-api
spec:
  selector:
    app: arcadia-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 5601
  type: ClusterIP