apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: arcadia-fe
  labels:
    app: arcadia-fe
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: arcadia-fe
  template:
    metadata:
      labels:
        app: arcadia-fe
    spec:
      containers:
        - image: gcu-profit-dev.kr-central-2.kcr.dev/arcadia-nextjs/arcadia-fe:74
          name: arcadia-fe
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          env:
          - name: NEXT_PUBLIC_S3_accessKeyId
            valueFrom:
              secretKeyRef:
                name: arcadia-nextjs-secret
                key: S3_accessKeyId
          - name: NEXT_PUBLIC_S3_secretAccessKey
            valueFrom:
              secretKeyRef:
                name: arcadia-nextjs-secret
                key: S3_secretAccessKey
          - name: NEXT_PUBLIC_S3_region
            valueFrom:
              secretKeyRef:
                name: arcadia-nextjs-secret
                key: S3_region
          - name: NEXT_PUBLIC_S3_bucketName
            valueFrom:
              secretKeyRef:
                name: arcadia-nextjs-secret
                key: S3_bucketName
      imagePullSecrets:
        - name: kic-registry
  strategy:
    blueGreen:
      activeService: arcadia-fe-active
      previewService: arcadia-fe-preview
      autoPromotionEnabled: true
