apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: arcadia-fe
  labels:
    app: arcadia-fe
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: arcadia-fe
  template:
    metadata:
      labels:
        app: arcadia-fe
    spec:
      containers:
        - image: gcu-profit-dev.kr-central-2.kcr.dev/arcadia-nextjs/arcadia-fe:62
          name: arcadia-fe
          ports:
            - containerPort: 3000
          # resources:
          #   requests:
          #     memory: "512Mi"
          #     cpu: "2000m"
          #   limits:
          #     memory: "512Mi"
          #     cpu: "2000m"
      imagePullSecrets:
        - name: kic-registry
  strategy:
    blueGreen:
      activeService: arcadia-fe-active
      previewService: arcadia-fe-preview
      autoPromotionEnabled: true