apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
data:
  master.cnf: |
    [mysqld]
    server-id=1
    log-bin=mysql-bin
    binlog-ignore-db=mysql
    binlog-ignore-db=information_schema
    binlog-ignore-db=performance_schema
    binlog-ignore-db=sys
    binlog_format=row
    default-authentication-plugin=mysql_native_password
  slave.cnf: |
    [mysqld]
    server-id=2
    relay-log=relay-log-bin
    log-bin=mysql-bin
    read_only=1
    binlog-ignore-db=mysql
    binlog-ignore-db=information_schema
    binlog-ignore-db=performance_schema
    binlog-ignore-db=sys
    binlog_format=row
    default-authentication-plugin=mysql_native_password