apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init-replication
data:
  init-replication.sh: |
    #!/bin/bash

    # Get the master status from the master DB
    MASTER_STATUS=$(mariadb -h mariadb-master -u root -pvmfhvlt! -e "SHOW MASTER STATUS\G")
    MASTER_LOG_FILE=$(echo "$MASTER_STATUS" | grep 'File:' | awk '{print $2}')
    MASTER_LOG_POS=$(echo "$MASTER_STATUS" | grep 'Position:' | awk '{print $2}')

    # Configure the slave with the master information
    mariadb -u root -pvmfhvlt! -e "STOP SLAVE;"
    mariadb -u root -pvmfhvlt! -e "CHANGE MASTER TO MASTER_HOST='mariadb-master', MASTER_USER='profit', MASTER_PASSWORD='vmfhvlt!', MASTER_LOG_FILE='$MASTER_LOG_FILE', MASTER_LOG_POS=$MASTER_LOG_POS;"
    mariadb -u root -pvmfhvlt! -e "START SLAVE;"
  set-server-id.sh: |
    #!/bin/bash
    server_id=$((${HOSTNAME##*-} + 2))
    sed -i "s/^server-id=.*/server-id=${server_id}/" /etc/mysql/conf.d/slave.cnf