apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-master
spec:
  serviceName: "mariadb-master"
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
      role: master
  template:
    metadata:
      labels:
        app: mariadb
        role: master
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: vmfhvlt!
        - name: MYSQL_REPLICATION_USER
          value: profit
        - name: MYSQL_REPLICATION_PASSWORD
          value: vmfhvlt!
        volumeMounts:
        - name: config
          mountPath: /etc/mysql/conf.d
        - name: mariadb-master
          mountPath: /var/lib/mysql
      volumes:
      - name: config
        configMap:
          name: mariadb-config
          items:
          - key: master.cnf
            path: master.cnf
  volumeClaimTemplates:
  - metadata:
      name: mariadb-master
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: nfs-client
      resources:
        requests:
          storage: 30Gi