apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-slave
spec:
  serviceName: "mariadb-slave"
  replicas: 2
  selector:
    matchLabels:
      app: mariadb
      role: slave
  template:
    metadata:
      labels:
        app: mariadb
        role: slave
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: vmfhvlt!
        - name: MYSQL_REPLICATION_USER
          value: profit
        - name: MYSQL_REPLICATION_PASSWORD
          value: vmfhvlt!
        - name: MYSQL_MASTER_SERVICE_HOST
          value: mariadb-master
        volumeMounts:
        - name: config
          mountPath: /etc/mysql/conf.d
        - name: mariadb-slave
          mountPath: /var/lib/mysql
      volumes:
      - name: config
        configMap:
          name: mariadb-config
          items:
          - key: slave.cnf
            path: slave.cnf
  volumeClaimTemplates:
  - metadata:
      name: mariadb-slave
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: nfs-client
      resources:
        requests:
          storage: 30Gi