apiVersion: v1
kind: Service
metadata:
  name: mariadb-master
  labels:
    app: mariadb
    role: master
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
    role: master
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-slave
  labels:
    app: mariadb
    role: slave
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
    role: slave
  